! UTEP Electronic Structure Lab (2020)
subroutine banner
WRITE(*,'(A)')" **************************************************************** "
WRITE(*,'(A)')"*      ___       ___       ___       ___       ___       ___     *"
WRITE(*,'(A)')"*     /\  \     /\__\     /\  \     /\  \     /\  \     /\  \    *"
WRITE(*,'(A)')"*    /::\  \   /:/  /    /::\  \   /::\  \   _\:\  \   /::\  \   *"
WRITE(*,'(A)')"*   /::\:\__\ /:/__/    /:/\:\__\ /\:\:\__\ /\/::\__\ /:/\:\__\  *"
WRITE(*,'(A)')"*   \/\:\/__/ \:\  \    \:\/:/  / \:\:\/__/ \::/\/__/ \:\ \/__/  *"
WRITE(*,'(A)')"*      \/__/   \:\__\    \::/  /   \::/  /   \:\__\    \:\__\    *"
WRITE(*,'(A)')"*               \/__/     \/__/     \/__/     \/__/     \/__/    *"
WRITE(*,'(A)')"*                  FLOSIC Public Release 2020                    *"
WRITE(*,'(A)')"* For published work employing this software, please cite        *"
WRITE(*,'(A)')"* these articles where it is relevant to your use.               *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* This software:                                                 *"
WRITE(*,'(A)')"* R. R. Zope, Y. Yamamoto, L. Basurto, C. M. Diaz, T. Baruah and *"
WRITE(*,'(A)')"* K. A. Jackson, FLOSIC software, https://http://flosic.org/,    *"
WRITE(*,'(A)')"* based on the NRLMOL code of M. R. Pederson.                    *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* NRLMOL basis:                                                  *"
WRITE(*,'(A)')"* D. Porezag and M. R. Pederson, Phys. Rev. A: At., Mol., Opt.   *"
WRITE(*,'(A)')"* Phys., 1999, 60, 2840–2847                                     *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* Variational mesh:                                              *"
WRITE(*,'(A)')"* M. R. Pederson and K. A. Jackson, Phys. Rev. B: Condens.       *"
WRITE(*,'(A)')"* Matter Mater. Phys., 1990, 41, 7453–7461.                      *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* FLOSIC-SCAN/rSCAN:                                             *"
WRITE(*,'(A)')"* Y. Yamamoto, C. M. Diaz, L. Basurto, K. A. Jackson, T. Baruah  *"
WRITE(*,'(A)')"* and R. R. Zope, J. Chem. Phys., 2019, 151, 154105;             *"
WRITE(*,'(A)')"* Y. Yamamoto, A. Salcedo, C. M. Diaz, M. S. Alam, T. Baruah and *"
WRITE(*,'(A)')"* R. R. Zope, Phys. Chem. Chem. Phys. 2020,                      *"
WRITE(*,'(A)')"* doi:10.1039/D0CP02717K                                         *"
WRITE(*,'(A)')" **************************************************************** "
end subroutine banner
