! UTEP Electronic Structure Lab (2020)
subroutine banner
WRITE(*,'(A)')" **************************************************************** "
WRITE(*,'(A)')"*      ___       ___       ___       ___       ___       ___     *"
WRITE(*,'(A)')"*     /\  \     /\__\     /\  \     /\  \     /\  \     /\  \    *"
WRITE(*,'(A)')"*    /::\  \   /:/  /    /::\  \   /::\  \   _\:\  \   /::\  \   *"
WRITE(*,'(A)')"*   /::\:\__\ /:/__/    /:/\:\__\ /\:\:\__\ /\/::\__\ /:/\:\__\  *"
WRITE(*,'(A)')"*   \/\:\/__/ \:\  \    \:\/:/  / \:\:\/__/ \::/\/__/ \:\ \/__/  *"
WRITE(*,'(A)')"*      \/__/   \:\__\    \::/  /   \::/  /   \:\__\    \:\__\    *"
WRITE(*,'(A)')"*               \/__/     \/__/     \/__/     \/__/     \/__/    *"
WRITE(*,'(A)')"*                  FLOSIC Public Release 2020                    *"
WRITE(*,'(A)')"* For published work employing this software, please cite        *"
WRITE(*,'(A)')"* these articles where it is relevant to your use. BibTex        *"
WRITE(*,'(A)')"* citations available in /doc/references/bib                     *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* This software:                                                 *"
WRITE(*,'(A)')"* R. R. Zope, Y. Yamamoto, L. Basurto, C. M. Diaz, T. Baruah and *"
WRITE(*,'(A)')"* K. A. Jackson, FLOSIC software, https://flosic.org/, based on  *"
WRITE(*,'(A)')"* the NRLMOL code of M. R. Pederson.                             *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* Parallelization:                                               *"
WRITE(*,'(A)')"* Y. Yamamoto, L. Basurto, C. M. Diaz, R. R. Zope, and T. Baruah,*"
WRITE(*,'(A)')"* “Self-interaction correction to density functional             *"
WRITE(*,'(A)')"* approximations using Fermi-Loewdin orbitals: Methodology and   *"
WRITE(*,'(A)')"* parallelization” (unpublished).                                *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* UTEP NRLMOL:                                                   *"
WRITE(*,'(A)')"* C. M. Diaz, L. Basurto, Y. Yamamoto, T. Baruah, and R. R. Zope,*"
WRITE(*,'(A)')"* UTEP-NRLMOL code (unpublished).                                *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* NRLMOL basis:                                                  *"
WRITE(*,'(A)')"* D. Porezag and M. R. Pederson, Phys. Rev. A: At. Mol. Opt.     *"
WRITE(*,'(A)')"* Phys. 60, 2840 (1999).                                         *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* Variational mesh:                                              *"
WRITE(*,'(A)')"* M. R. Pederson and K. A. Jackson, Phys. Rev. B: Condens.       *" 
WRITE(*,'(A)')"* Matter Mater. Phys. 41, 7453 (1990).                           *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* FLOSIC and FLOSIC algorithm:                                   *"
WRITE(*,'(A)')"* M. R. Pederson, A. Ruzsinszky, and J. P. Perdew, J. Chem. Phys.*"
WRITE(*,'(A)')"* 140, 121103 (2014); Z. Yang, M. R. Pederson, and J. P. Perdew, *"
WRITE(*,'(A)')"* Phys. Rev. A 95, 052505 (2017).                                *"
WRITE(*,'(A)')"*                                                                *" 
WRITE(*,'(A)')"* FLOSIC-SCAN/-rSCAN, FLOSIC-libxc, or integration by parts:     *"
WRITE(*,'(A)')"* Y. Yamamoto, C. M. Diaz, L. Basurto, K. A. Jackson, T. Baruah  *"
WRITE(*,'(A)')"* and R. R. Zope, J. Chem. Phys. 151, 154105 (2019); Y. Yamamoto,*"
WRITE(*,'(A)')"* A. Salcedo, C. M. Diaz, M. S. Alam, T. Baruah and R. R. Zope,  *"
WRITE(*,'(A)')"* Phys. Chem. Chem. Phys. 22, 18060 (2020).                      *"
WRITE(*,'(A)')"*                                                                *"
WRITE(*,'(A)')"* ADSIC, Slater averaging of SIC potential, FLOSIC-KLI:          *"
WRITE(*,'(A)')"* C. M. Diaz, T. Baruah, and R. R. Zope, Phys. Rev. A 103, 042811*"
WRITE(*,'(A)')"* (2021); C. M. Diaz, P. Suryanarayana, Q. Xu, T. Baruah, J. E.  *"
WRITE(*,'(A)')"* Pask, and R. R. Zope, J. Chem. Phys. 154, 084112 (2021).       *"
WRITE(*,'(A)')" **************************************************************** "
end subroutine banner
