! UTEP Electronic Structure Lab (2020)
SUBROUTINE CHECK_MOLDEN
!  USE DEBUG1
  LOGICAL :: EXIST
!
! CHECK FOR PREVIOUS EXISTENCE OF MOLDEN FILE
!
!  CALL TRACER('IN CHECK_MOLDEN')
  INQUIRE(FILE='CLUSTER.MOLDEN',EXIST=EXIST)
  IF(.NOT.EXIST)THEN

!     --- CREATE/OPEN THE MOLDEN OUTPUT FILE AND ---
!     --- MAKE SURE THAT IS EMPTY ! ---
!
!    CALL TRACER('CLUSTER.MOLDEN DOES NOT EXIST')
    OPEN(42, FILE='CLUSTER.MOLDEN', STATUS='UNKNOWN')
    REWIND(42)
    ENDFILE(42)
    REWIND(42)
    WRITE(42,'(A)') '[Molden Format]'
    CLOSE(42)
    CALL MOLDENDRV('XYZ')
  ENDIF

END SUBROUTINE CHECK_MOLDEN
