C UTEP Electronic Structure Lab (2020)
C
C ***************************************************************
C
        SUBROUTINE CLSGRP(MGP,R)
C ORIGINAL VERSION BY MARK R PEDERSON (1996)
C
C CLSGROUP FINDS ALL THE GROUP OPERATIONS GENERATED BY THE MGP
C INPUT GROUP ELEMENTS
C
         IMPLICIT REAL*8  (A-H,O-Z)
         DIMENSION R(3,3,121)
         SAVE
C
C GENERATE GROUP MATRIX:
C
         NGP=MGP 
   10    CONTINUE
          MGP=NGP
          IF (NGP.GT.120) THEN
           PRINT *,'CLSGRP: NUMBER OF GROUP ELEMENTS > 120'
           CALL STOPIT
          END IF
          DO IGP=1,MGP
           DO JGP=1,MGP
            NGP=NGP+1
            DO I=1,3
             DO J=1,3
              R(J,I,NGP)=0.0D0
              DO K=1,3
               R(J,I,NGP)=R(J,I,NGP)+R(J,K,IGP)*R(K,I,JGP)
              END DO
             END DO
            END DO
            ITOT=0
            DO KGP=1,NGP-1
             ERROR=0.0D0
             DO I=1,3
              DO J=1,3
               ERROR=ERROR+ABS(R(J,I,NGP)-R(J,I,KGP))
              END DO
             END DO
             IF(ERROR .LT. 1.0D-4) ITOT=ITOT+1
            END DO
            IF (ITOT.GT.0) NGP=NGP-1
           END DO
          END DO
          IF (NGP.GT.MGP) GOTO 10
         CONTINUE
         RETURN
        END
