C UTEP Electronic Structure Lab (2020)
C
       SUBROUTINE GTBARE(IFNCT,BARE,GAUS)
       use common2,only : BFCON, BFALP, N_BARE, N_CON, LSYMMAX
! Conversion to implicit none.  Raja Zope Thu Aug 17 14:34:48 MDT 2017

!      INCLUDE  'PARAMAS'  
       INCLUDE  'PARAMA2'  
       INTEGER :: IFNCT, I_BARE, IANG, IBARE, IEND, IFC, ISHIFT, ISIZE,
     & L1, LMAX, LMAX1, NB
       REAL*8 :: BARE , GAUS, ALP2R, CONTR, PANG, PTS, RSQR
       SAVE
       LOGICAL IUPDAT,ICOUNT,FIRST,IALLCTR,IBARCTR,ITMPCTR
       DIMENSION IALLCTR(MAX_CON,3),IBARCTR(MAX_CON,3)
       DIMENSION PTS(NSPEED,3),GAUS(NSPEED),RSQR(NSPEED)
       DIMENSION BARE(NSPEED,6,3,MAX_CON)
       DIMENSION PANG(NSPEED,10,10),ALP2R(NSPEED,3)
       DIMENSION ISIZE(3),IEND(3),ISHIFT(3)
C
       DATA ISIZE /1,3,6/
       DATA IEND  /1,4,10/
       DATA ISHIFT/0,1,4/
       DATA FIRST/.TRUE./
       LMAX=LSYMMAX(IFNCT)
       LMAX1=LMAX+1
C INITIALIZE GRAD AND IALLCTR
C
       DO L1=1,LMAX1
        DO NB=1,N_CON(L1,IFNCT)
         DO IANG=1,ISIZE(L1)
          DO IBARE=1,N_BARE(IFNCT)
            BARE(IBARE,IANG,L1,NB)= 0.0D0
          END DO
         END DO
        END DO
       END DO
C
C LOOP OVER ALL BARE GAUSSIANS
C
       IUPDAT=.FALSE.
       DO 100 I_BARE=1,N_BARE(IFNCT)
          GAUS(I_BARE)=BFALP(I_BARE,IFNCT)
C
C WAVEFUNCTION
C
        DO L1=1,LMAX1
         DO NB=1,N_CON(L1,IFNCT)
           CONTR=BFCON(I_BARE,NB,L1,IFNCT)
           DO IANG=1,ISIZE(L1)
            IFC=IANG+ISHIFT(L1)
             BARE(I_BARE,IANG,L1,NB)=BARE(I_BARE,IANG,L1,NB)+CONTR
           END DO
         END DO
        END DO
  100  CONTINUE
       RETURN
       END
