! UTEP Electronic Structure Lab (2020)
SUBROUTINE NORMH(MODE)
! NORMALIZATION OF HAMILTONIAN
! LUIS BASURTO (2014)
! CALCULATE Hij=Hij/SQRT(Sii*Sjj)
! FOR HAMILTONIAN    MODE=1
! FOR OVERLAP        MODE=3
! DO THE INVERSE OPERATION (UNNORMAILZE)
! FOR HAMILTONIAN    MODE=2
! FOR OVERLAP        MODE=4
USE HSTOR1,only : HSTOR
USE COMMON8,only : N_REP,NS_TOT
USE normham 
IMPLICIT NONE
INTEGER,INTENT(IN) :: MODE
INTEGER            :: I,J,K,MDH,MDHTOT,MDHTOT2,MSPN,ISPN,IREP,NBAS,OFFSET
!REAL*8,ALLOCATABLE :: DIAG(:)
REAL*8             :: DH
REAL*8             :: ADD
!LOGICAL            :: FIRST
!DATA    FIRST/.TRUE./
logical :: exist, first=.true.
!WRITE(6,*)'normh ', first, ndiag

call flush(6)
IF (FIRST) THEN
   ndiag=0
   DO IREP=1,N_REP
     NBAS=NS_TOT(IREP)
     ndiag=ndiag+NBAS
   END DO

   offset=ndiag
   OPEN(20,FILE='OVLBABY',FORM='UNFORMATTED',STATUS='UNKNOWN')
   READ(20) MDHTOT2

   ALLOCATE(DIAG(ndiag))
   READ(20)(HSTOR(I,1),I=1,MDHTOT2)
   CLOSE(20)
! GET DIAGONAL ELEMENTS
   K=1
   OFFSET=0
   DO IREP=1,N_REP
     NBAS=NS_TOT(IREP)
     DO I=1,NBAS
       DO J=I,NBAS
         IF(I==J) THEN
           DIAG(I+OFFSET)=HSTOR(K,1)
         ENDIF
         K=K+1
       END DO
     END DO
     OFFSET=OFFSET+NBAS
   END DO
   FIRST=.FALSE.
END IF

ADD=0.0d0
DO I=1,ndiag
     ADD=ADD+DIAG(I)
END DO

!WRITE(6,*)'normh ', add

call flush(6)


!IF(MODE==2)THEN
!  IF(MDHTOT2/=MDHTOT) THEN
!    WRITE(6,*)'NORMH ERROR:FILES NOT COMAPTIBLE'
!    CALL STOPIT
!  ENDIF
!ENDIF

SELECT CASE(MODE)
! NORMAILZE HAMILTONIAN
  CASE (1)
OPEN(19,FILE='HAMOLD',FORM='UNFORMATTED',STATUS='UNKNOWN')
READ(19) MDHTOT,MSPN
!write(6,*) 'hamold', MDHTOT,MSPN
    OPEN(21,FILE='HAMNORM',FORM='UNFORMATTED',STATUS='UNKNOWN')
    WRITE(21)MDHTOT,MSPN
    DO ISPN=1,MSPN
      READ(19)(HSTOR(I,2),I=1,MDHTOT)
      K=1
      OFFSET=0
      DO IREP=1,N_REP
        NBAS=NS_TOT(IREP)
        DO I=1,NBAS
          DO J=I,NBAS
            HSTOR(K,2)=HSTOR(K,2)/SQRT(DIAG(I+OFFSET)*DIAG(J+OFFSET))
            K=K+1
          END DO
        END DO
        OFFSET=OFFSET+NBAS
      END DO
      WRITE(21)(HSTOR(I,2),I=1,MDHTOT)
    END DO
    CLOSE(19)
    CLOSE(21)
    CALL SYSTEM('mv HAMNORM HAMOLD')
! UNNORMAILZE HAMILTONIAN
  CASE (2)
OPEN(19,FILE='HAMOLD',FORM='UNFORMATTED',STATUS='UNKNOWN')
READ(19) MDHTOT,MSPN
!write(6,*) 'hamold', MDHTOT,MSPN
call flush(6)
    OPEN(21,FILE='HAMNORM',FORM='UNFORMATTED',STATUS='UNKNOWN')
    WRITE(21)MDHTOT,MSPN
 
    DO ISPN=1,MSPN
 
      READ(19)(HSTOR(I,2),I=1,MDHTOT)
      K=1
      OFFSET=0
      DO IREP=1,N_REP
        NBAS=NS_TOT(IREP)
        DO I=1,NBAS
          DO J=I,NBAS
            HSTOR(K,2)=HSTOR(K,2)*SQRT(DIAG(I+OFFSET)*DIAG(J+OFFSET))
            K=K+1
          END DO
        END DO
        OFFSET=OFFSET+NBAS
      END DO
      WRITE(21)(HSTOR(I,2),I=1,MDHTOT)
    END DO
    CLOSE(19)
    CLOSE(21)
    CALL SYSTEM('mv HAMNORM HAMOLD')
! NORMALIZE OVERLAP
!  CASE (3)
!    REWIND(20)
!    WRITE(20)MDHTOT
!    K=1
!    DO I=1,MDH
!      DO J=I,MDH
!        HSTOR(K,1)=HSTOR(K,1)/SQRT(DIAG(I)*DIAG(J))
!        K=K+1
!      END DO
!    END DO
!    WRITE(20)(HSTOR(I,1),I=1,MDHTOT)
!! UNNORMALIZE OVERLAP
!  CASE (4)
!    REWIND(20)
!    WRITE(20)MDHTOT
!    K=1
!    DO I=1,MDH
!      DO J=I,MDH
!        HSTOR(K,1)=HSTOR(K,1)*SQRT(DIAG(I)*DIAG(J))
!        K=K+1
!      END DO
!    END DO
!    WRITE(20)(HSTOR(I,1),I=1,MDHTOT)
END SELECT
CLOSE(20)
!DEALLOCATE(DIAG)
END SUBROUTINE NORMH
