C UTEP Electronic Structure Lab (2020)
      SUBROUTINE PASLM_MSH(MODE)
      use debug1
      use mpidat1, only : IRANK
      use SICMAT, only : SIC
      use mesh1,only : NMSH,FO_MESH
      use FRM, only : BFRM,RESULTS,LFRM
! Conversion to implicit none.  Raja Zope Thu Aug 17 14:34:56 MDT 2017

!      INCLUDE  'PARAMAS'  
       INCLUDE  'PARAMA2'  
      INCLUDE 'mpif.h'
!     INCLUDE 'commons.inc'
      save
      INTEGER :: IERR,JWF,LFM,LFN,LSPN,MISTAKES,MPTS,NMAX,LPTS
      REAL*8 :: APT1,APT2,BUF0,BUF1,BUF2,BUF3,RPTS,SICP,WMSA
      PARAMETER (NMAX=MPBLOCK)
      INTEGER TID,ITRANS(4),MODE,TAG,I,SUM1
      INTEGER IRECVSTAT(MPI_STATUS_SIZE)
      LOGICAL BUF
!      DIMENSION WMSA(NMAX),SICP(NMAX),RPTS(3,NMAX)
!      DIMENSION BUF1(NMAX),BUF2(NMAX),BUF3(3,NMAX),BUF0(3)
      DIMENSION BUF(NMSH)
      DIMENSION MISTAKES(2)
C     COMMON/MIXPOT/POTIN(MAX_PTS*MXSPN),POT(MAX_PTS*MXSPN)
C     COMMON/TMP1/COULOMB(MAX_PTS),RHOG(MAX_PTS,10,MXSPN)
C     COMMON/TMP2/PSIG(NMAX,10,MAX_OCC)
C    &  ,PTS(NSPEED,3),GRAD(NSPEED,10,6,MAX_CON,3)
C    &  ,RVECA(3,MX_GRP),ICOUNT(MAX_CON,3)
!      COMMON/SICMAT/SIC(MAX_OCC,MAX_OCC,MXSPN)
!      COMMON/FRM/BFRM(3,MAX_OCC,MXSPN),RESULTS(13, MAX_OCC,MXSPN),
!     &   LFRM(MXSPN),DEBDAX(3,MAX_OCC,MXSPN)
       DATA MISTAKES/0,0/
       IF (IRANK.EQ.0) THEN
        PRINT *,'FATAL: PASLMSIC CALLED BY MANAGER'
        CALL STOPIT
       END IF

      IF (MODE .EQ. 1 ) THEN
       TAG=2401
       CALL MPI_RECV(ITRANS(1),4,MPI_INTEGER,
     &               0,TAG,MPI_COMM_WORLD,IRECVSTAT,IERR)
       LSPN = ITRANS(1)
       LFM  = ITRANS(2)
!       LFM  = LFN
       MPTS = ITRANS(3)
       LPTS = ITRANS(4)
C      PRINT*,IRANK,'PAS RECV   LFM IS ONE :',LFM,LFN
       CALL GTTIME(APT1)
!       IF(LFM.EQ.0)THEN
C        PRINT*,IRANK,'PAS BEFORE LFM IS ZERO:',LFM,LFN
!         LFM=MAX(LFN,LFM)
!         MISTAKES(1)=MISTAKES(1)+1
!         IF(MISTAKES(1).GT.MISTAKES(2))THEN
!           MISTAKES(2)=MISTAKES(1)*2
!           PRINT*,'LFM MISTAKES:',IRANK,MISTAKES
!         END IF
!       END IF
!       WRITE(6+IRANK,*)'WORKING',LSPN,LFM,MPTS,LPTS
       CALL SICLM_MSH(LSPN,LFM,MPTS,LPTS)
!       WRITE(6+IRANK,*)'FINISHED',LSPN,LFM,MPTS,LPTS
C                 PRINT*,IRANK,'PAS AFTER  LFM IS ZERO:',LFM
       CALL GTTIME(APT2)
C      PRINT*,'I AM RANK:',IRANK,' AND I AM DONE',APT2-APT1,MPTS
       TAG=1
       CALL MPI_SSEND(IRANK,1,MPI_INTEGER,0,TAG,MPI_COMM_WORLD,IERR)
!       WRITE(6+IRANK,*)'FINISHED TELLING MOM I AM DONE'
      END IF

      IF (MODE .EQ. 2 ) THEN
C      PRINT*,IRANK,' REDUCE',LFM,LSPN
!       TAG=2501
!       SUM1=0
!       DO I=1,NMSH
!         IF(FO_MESH(I)==1) SUM1=SUM1+1
!       ENDDO
!       CALL TRACER('SUM1',SUM1)
!       CALL MPI_BARRIER(MPI_COMM_WORLD,IERR)
       CALL MPI_REDUCE(FO_MESH,BUF,NMSH,
     &                  MPI_LOGICAL,MPI_LOR,0,
     &                  MPI_COMM_WORLD,IERR)
!       DO JWF=1,MAX_OCC
!         SIC(JWF,LFM,LSPN)= BUF(JWF)       
!       END DO
C      PRINT*,'REDUCE RETURNING RANK',IRANK
      END IF
      RETURN
      END
