C UTEP Electronic Structure Lab (2020)
       SUBROUTINE READMESH(JSPN,IFRM,POSITION,DST)       
C ORIGINAL VERSION BY MARK R PEDERSON JULY 1989
        use mesh1,only : NMSH,RMSH,WMSH
! Conversion to implicit none.  Raja Zope Thu Aug 17 14:35:00 MDT 2017

!      INCLUDE  'PARAMAS'  
       INCLUDE  'PARAMA2'  
       INTEGER :: LMXX, I, J, JCALC, NFILE, MAXANG, LMX2, LMX_OLD,
     & MAXRAD, NANG, NPOW, NRAD
       REAL*8 :: SYMBOL , POSITION, DST, AFUDGE, AMAX, AMIN, ANGLE,
     & DOMEGA, ERRMAX, PI, RAD, RMAX, RMIN, VOL, WTRAD
!        INCLUDE 'commons.inc'
        save
        DIMENSION POSITION(3)
        CHARACTER*15 VNAME
        LOGICAL EXIST
        INTEGER JSPN, IFRM
        
        
        INQUIRE (FILE='FODONMSH',EXIST=EXIST)
        IF(.NOT. EXIST) RETURN
C        INQUIRE (FILE='FAST',EXIST=EXIST)
        VNAME(1:15)='VMSHFOD'
        WRITE(VNAME(8:11),17)JSPN
        WRITE(VNAME(12:15),17)IFRM
 17     FORMAT(I4.4)
        PRINT*,'OPENING VNAME:',VNAME,NFILE
        IF(JSPN.EQ.0)THEN
        !<LA: why is this opened then closed?
          OPEN(99,FILE='VMOLD',FORM='UNFORMATTED',STATUS='UNKNOWN')
          CLOSE(99)
          RETURN
        ELSE IF(DST.GT. 0.5D0) THEN
          OPEN(99,FILE=VNAME,FORM='UNFORMATTED',STATUS='UNKNOWN')
          PRINT*,' READING MESH FOR', JSPN, IFRM
          REWIND(99)
          READ(99) NMSH,JCALC
          READ(99)((RMSH(J,I),J=1,3),I=1,NMSH)
          READ(99)(WMSH(I),I=1,NMSH)
          CLOSE(99)
       ELSE      
          PRINT*,' GENERATING RADIAL MESH FOR CORE STATE:'
          PRINT*,' ', JSPN,IFRM,DST
          CALL SICMESH(POSITION)
       END IF
       PRINT*,' VMSHFOD INFO:', VNAME 
       PRINT*,' VMSHFOD INFO:', DST,POSITION
       PRINT*,' VMSHFOD INFO:', NMSH
       
       !CALL STOPIT
       
       RETURN  
       END


       SUBROUTINE SICMESH(POSITION)
C ANALYZE BY MRP JULY 1998
C * CHARGES WITHIN A SPHERE
C
C ANGULAR DECOMPOSITION FOR WAVEFUNCTIONS       
C
       use mesh1, only : nmsh, rmsh, wmsh
! Conversion to implicit none.  Raja Zope Thu Aug 17 14:35:00 MDT 2017

!      INCLUDE  'PARAMAS'  
       INCLUDE  'PARAMA2'  
       INTEGER :: LMXX, I, J, JCALC, NFILE, MAXANG, LMX2, LMX_OLD,
     & MAXRAD, NANG, NPOW, NRAD
       INTEGER :: MAXSPH,NMAX,LSIZ,MXCHG
       REAL*8 :: SYMBOL , POSITION, DST, AFUDGE, AMAX, AMIN, ANGLE,
     & DOMEGA, ERRMAX, PI, RAD, RMAX, RMIN, VOL, WTRAD
C       INCLUDE 'commons.inc'
       save
       PARAMETER (NMAX=MPBLOCK)
       PARAMETER (LMXX=20)
       PARAMETER (LSIZ=(LMXX+1)**2)
       PARAMETER (MAXANG=((2*LMXX+1)*(LMXX+1)))
       PARAMETER (MAXSPH=500)
       PARAMETER (MAXRAD=1000)
       PARAMETER (MXCHG=56)
       CHARACTER*80 LINE
       LOGICAL LMKFIL,EXIST
       LOGICAL IUPDAT,ICOUNT
C
C SCRATCH COMMON BLOCK FOR LOCAL ARRAYS
C
       DIMENSION ANGLE(3,MAXANG),RAD(200),WTRAD(200)
       DIMENSION DOMEGA(MAXANG)
       DIMENSION POSITION(3)
       INQUIRE(FILE='FODONMSH',EXIST=EXIST)
       IF(.NOT. EXIST) RETURN
       RMIN=0.0D0
       ERRMAX=1.0D-8
       AMIN=0.1  
       RMAX=SQRT(4.0d0/AMIN)
       AMAX=100000.
       AFUDGE=1.2
       NPOW=4
       CALL RADMSH(MAXRAD,RMIN,RMAX,ERRMAX,AMIN,AMAX,AFUDGE,NPOW,
     &                NRAD,RAD,WTRAD)
       LMX_OLD=0
       NMSH=0
       DO I=1,NRAD
                        LMX2=27
       IF(RAD(I).LT.0.2)LMX2=15
       IF(LMX2.NE.LMX_OLD)THEN
       CALL ANGMSH(MAXANG,LMX2,NANG,ANGLE,DOMEGA)
                        LMX_OLD=LMX2
       END IF
              DO J=1,NANG
              NMSH=NMSH+1
              WMSH(NMSH)=DOMEGA(J)*WTRAD(I)
              RMSH(1,NMSH)=ANGLE(1,J)*RAD(I)+POSITION(1)
              RMSH(2,NMSH)=ANGLE(2,J)*RAD(I)+POSITION(2)
              RMSH(3,NMSH)=ANGLE(3,J)*RAD(I)+POSITION(3)
              VOL=VOL+WTRAD(I)*DOMEGA(J)
              END DO
       END DO
          PI=4.0D0*ATAN(1.0D0)
          PRINT*,VOL,4.0D0*PI*RMAX**3/3.0D0 ,NMSH, 'SMALL MESH'
       RETURN
       END
