! UTEP Electronic Structure Lab (2020)
!
! ******************************************************************
!
SUBROUTINE SALLBAS3(BASIS,IZNUC,ALP,CON,NALP,NBASF)
!
! LUIS BASURTO, OCTOBER 2013
! BASIS SET GENERATOR FOR ALL-ELECTRON CALCULATIONS
! DATA STORED IN FILES ACCORDING TO DESIRED BASIS
!
!
! Conversion to implicit none.  Raja Zope Sun Aug 20 10:02:06 MDT 2017

!      INCLUDE  'PARAMAS'  
       INCLUDE  'PARAMA2'  
       INTEGER :: IZNUC, NBASF, I, J, K
       REAL*8 :: ALP , CON
     DIMENSION ALP(MAX_BARE),CON(MAX_BARE,MAX_CON,3),NBASF(2,3) 
     INTEGER :: NALP,BASIS,ATOM
     CHARACTER*4   :: ATOMNAME     
     CHARACTER*40  :: FILENAME
     CHARACTER*80  :: BASIS_PATH
     CHARACTER*120 :: FULLNAME
     LOGICAL EXIST
     SAVE
!
     IF (IZNUC.LT.0) THEN 
       PRINT *,'SALLBAS: Z < 0 IS NOT SUPPORTED'
       CALL STOPIT
     END IF
!
! GET FILE NAME FOR DESIRED BASIS SET
!
     CALL GETBASNAME(BASIS,FILENAME)
     CALL GET_ENVIRONMENT_VARIABLE('NRLMOL_BASIS',BASIS_PATH)
     FULLNAME=TRIM(BASIS_PATH)//TRIM(FILENAME)
     WRITE(6,*)'USING BASIS FILE:',TRIM(FULLNAME)
!
! PROCESS FILE THAT CONTAINS BASIS
!
     INQUIRE(FILE=TRIM(FULLNAME),EXIST=EXIST)
     IF(.NOT.EXIST) THEN
        WRITE(6,*) 'FILE:',TRIM(FULLNAME),' NOT FOUND'
        CALL STOPIT
     ENDIF       
     OPEN(18,FILE=TRIM(FULLNAME))
     DO
       READ(18,*,END=100)ATOM
       READ(18,*) ATOMNAME
!      WRITE(6,*) 'READING ATOM ',ATOMNAME       
       READ(18,*) NALP
       IF(NALP.GT.MAX_BARE)THEN
         WRITE(6,*)'SALLBAS3:MAX_BARE MUST BE AT LEAST:',NALP
         CALL STOPIT
       ENDIF
       READ(18,*)(NBASF(1,I),I=1,3)
       DO I=1,3
         NBASF(2,I)=0
       ENDDO
       READ(18,*)(ALP(I),I=1,NALP)
       DO I=1,3
         IF(NBASF(1,I).NE.0)THEN
           DO J=1,NBASF(1,I)
              READ(18,*)(CON(K,J,I),K=1,NALP)
           ENDDO
         ENDIF
       ENDDO
       IF(ATOM.EQ.IZNUC) THEN
! FOUND ATOM IN FILE
          CLOSE(18)
          RETURN
       ENDIF
     ENDDO
100  CLOSE(18)
     WRITE(6,*) 'ATOM ',IZNUC,' NOT FOUND IN BASIS'
     WRITE(6,*) 'USING FROM DEFAULT BASIS SET'
     CALL SALLBAS(IZNUC,ALP,CON,NALP,NBASF)
     RETURN
END SUBROUTINE SALLBAS3

