! UTEP Electronic Structure Lab (2020)
SUBROUTINE TRIGGER
IMPLICIT NONE
INCLUDE 'mpif.h'

INTEGER,PARAMETER :: ROOT=0,TAG=0
INTEGER :: JOB,IERR,IRECVSTAT(MPI_STATUS_SIZE) 

JOB=0
DO WHILE (JOB>=0)
  CALL MPI_RECV(JOB,1,MPI_INTEGER,0,TAG,MPI_COMM_WORLD,IRECVSTAT,IERR)
  IF(JOB==1) CALL SCALA_CALL(JOB)
END DO
RETURN
END SUBROUTINE TRIGGER
